from enum import Enum


class AnomalySeverity(str, Enum):
    CRITICAL = "CRITICA"
    HIGH = "ALTA"
    MEDIUM = "MEDIA"
    LOW = "BAIXA"


class Activity(str, Enum):
    MIXING = "MIXING"
    EQ_ADJUSTMENT = "EQ_ADJUSTMENT"
    MONITORING = "MONITORING"
    IDLE = "IDLE"
    BEAT_MATCHING = "BEAT_MATCHING"
    SYNCED_MIX = "SYNCED_MIX"
    TRANSITIONING = "TRANSITIONING"


# Fader
FADER_ACTIVE_MIN_POSITION = 0.15

# Clipping (canal vermelho)
CLIPPING_RED_RATIO_THRESHOLD = 0.15
CLIPPING_HUE_LOW_1 = 0
CLIPPING_HUE_HIGH_1 = 10
CLIPPING_HUE_LOW_2 = 170
CLIPPING_HUE_HIGH_2 = 180
CLIPPING_SAT_MIN = 100
CLIPPING_VAL_MIN = 100

# Mão
HAND_VELOCITY_THRESHOLD = 0.04
INACTIVITY_TIMEOUT_SECONDS = 30.0

# Ritmo
RHYTHM_WINDOW_FRAMES = 90
SYNC_PHASE_TOLERANCE_FRAMES = 3
SYNC_CORRELATION_MIN = 0.6

# Classificação
ACTIVITY_SMOOTHING_FRAMES = 15
MIXING_VELOCITY_MIN = 0.01
BEAT_MATCHING_VELOCITY_MIN = 0.03
